sudo: required
services:
  - docker

before_install:
  - docker build -t torlowski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true torlowski/react-test npm test 

after_success:
  - docker build -t torlowski/multi-client -f ./client/Dockerfile.prod ./client 
  - docker build -t torlowski/multi-nginx -f ./client/Dockerfile.prod ./nginx
  - docker build -t torlowski/multi-server -f ./client/Dockerfile.prod ./server
  - docker build -t torlowski/multi-worker -f ./client/Dockerfile.prod ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push torlowski/multi-client
  - docker push torlowski/multi-nginx
  - docker push torlowski/multi-server
  - docker push torlowski/multi-worker